apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: nfs-vol6
  labels:
    path: nfsshare6
    type: redis-nfs
    app: redis
    podindex: "5"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.24.132.110
    path: "/opt/logs/redis_test/n6"